import '../styles/global.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Nav from "../components/Nav";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'letsCode',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav /> 
        <div className='main'>
          <div className='gradient' />
        </div>
        <div className='app'>{children}</div>
      </body>
    </html>
  )
}
