"use client";
import React from 'react';
import Head from 'next/head';
import { app,firestore } from '../../firebaseConfig';
import { getAuth, createUserWithEmailAndPassword, GoogleAuthProvider, GithubAuthProvider, signInWithPopup } from 'firebase/auth';
import { useState } from 'react';
import { doc, setDoc } from "firebase/firestore";
import '../../styles/global.css'
import Image from 'next/image';

const Register: React.FC = () => {
    const auth = getAuth(app);
    const googleProvider = new GoogleAuthProvider();
    const githubProvider = new GithubAuthProvider();

    const [username, setUsername] = useState('');
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    
    const  signUp =  () => {
        if(!email || !password){
            alert("all feilds are required")
        }else{
            createUserWithEmailAndPassword(auth, email, password)
            .then(async (response) => {
                //console.log(response.user);
                const userData = {
                    uid: response.user.uid,
                    email:email,
                    displayName: username,
                    createdAt: Date.now(),
                    updatedAt: Date.now(),
                    solvedProblems: [],
                    solvedprob: {
                        easy: 0,
                        medium: 0,
                        hard: 0,
                      },
                    ActivityInd:[
                        {
                            date:new Date(),
                            count:0
                        }
                    ],
                    imgUrl:"/assets/images/avatar.png"
                };
                await setDoc(doc(firestore, "users", response.user.uid), userData);
                //console.log(userData);
                window.location.href = '/'; 
            })
            .catch((err)=>{
                alert("failed to signUp with email and password")
            })
        }
        
    }

    const signUpWithGoogle = () => {
        signInWithPopup(auth, googleProvider)
            .then(async (response) => {
                const userData = {
                    uid: response.user.uid,
                    email:response.user.email,
                    displayName: response.user.displayName,
                    createdAt: Date.now(),
                    updatedAt: Date.now(),
                    solvedProblems: [],
                    solvedprob: {
                        easy: 0,
                        medium: 0,
                        hard: 0,
                      },
                      ActivityInd:[
                          {
                              date:new Date(),
                              count:0
                          }
                      ],
                      imgUrl:response.user.photoURL
                };
                await setDoc(doc(firestore, "users", response.user.uid), userData);
                window.location.href = '/';
            })
            .catch((err)=>{
                alert("failed to signUp with google")
            })
            
    }

    const signUpWithGithub = () => {
        signInWithPopup(auth, githubProvider)
            .then(async (response) => {
                const userData = {
                    uid: response.user.uid,
                    email:response.user.email,
                    displayName: response.user.displayName,
                    createdAt: Date.now(),
                    updatedAt: Date.now(),
                    solvedProblems: [],
                    solvedprob: {
                        easy: 0,
                        medium: 0,
                        hard: 0,
                      },
                      ActivityInd:[
                          {
                              date:new Date(),
                              count:0
                          }
                      ],
                      imgUrl:response.user.photoURL
                };
                await setDoc(doc(firestore, "users", response.user.uid), userData);
                window.location.href = '/';
            })
            .catch(err => {
                alert('failed to signUp with Github');
            })
    }

    return (
        <div className="flex items-center justify-center">
            <Head>
                <title>Next CRUD AUTH</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <div className="form-container">
                    <p className="title">Welcome back</p>
                    <div className="form">
                        <input type="text"
                            className="input" 
                            placeholder="Name" 
                            onChange={(event) => setUsername(event.target.value)}
                            value={username}/>

                        <input type="email"
                            className="input" 
                            placeholder="Email" 
                            onChange={(event) => setEmail(event.target.value)}
                            value={email}/>

                        <input type="password" 
                            className="input" 
                            placeholder="Password"
                            onChange={(event) => setPassword(event.target.value)}
                            value={password}
                            />
                        <button className="form-btn" onClick={signUp}>Sign Up</button>
                    </div>
                    <a href='/signIn' className="sign-up-label">
                        Don't have an account?<span className="sign-up-link">Sign In</span>
                    </a>
                    
                    <div className="buttons-container">
                        <button onClick={signUpWithGithub}>
                            <div className="apple-login-button">
                            <Image
                                    src="/assets/images/github.png" 
                                    alt="logo"
                                    width={25}
                                    height={25}
                                    className="object-contain rounded-full"
                                />
                                <span>Sign Up with GitHub</span>
                            </div>
                        </button>
                        <button onClick={signUpWithGoogle}>
                            <div className="google-login-button">
                                <svg stroke="currentColor" fill="currentColor" stroke-width="0" version="1.1" x="0px" y="0px" className="google-icon" viewBox="0 0 48 48" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
                                    <path fill="#FFC107" d="M43.611,20.083H42V20H24v8h11.303c-1.649,4.657-6.08,8-11.303,8c-6.627,0-12-5.373-12-12
                            c0-6.627,5.373-12,12-12c3.059,0,5.842,1.154,7.961,3.039l5.657-5.657C34.046,6.053,29.268,4,24,4C12.955,4,4,12.955,4,24
                            c0,11.045,8.955,20,20,20c11.045,0,20-8.955,20-20C44,22.659,43.862,21.35,43.611,20.083z"></path>
                                    <path fill="#FF3D00" d="M6.306,14.691l6.571,4.819C14.655,15.108,18.961,12,24,12c3.059,0,5.842,1.154,7.961,3.039l5.657-5.657
                            C34.046,6.053,29.268,4,24,4C16.318,4,9.656,8.337,6.306,14.691z"></path>
                                    <path fill="#4CAF50" d="M24,44c5.166,0,9.86-1.977,13.409-5.192l-6.19-5.238C29.211,35.091,26.715,36,24,36
                            c-5.202,0-9.619-3.317-11.283-7.946l-6.522,5.025C9.505,39.556,16.227,44,24,44z"></path>
                                    <path fill="#1976D2" d="M43.611,20.083H42V20H24v8h11.303c-0.792,2.237-2.231,4.166-4.087,5.571
                            c0.001-0.001,0.002-0.001,0.003-0.002l6.19,5.238C36.971,39.205,44,34,44,24C44,22.659,43.862,21.35,43.611,20.083z"></path>
                                </svg>
                                <span>Sign Up with Google</span>
                            </div>
                        </button>
                    </div>
                </div>
            </main>
        </div>
    )
}

export default Register;
